name: Docker Build Test

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Backend Image
      run: |
        docker build -t backend ./backend

    - name: Build Frontend Image
      run: |
        docker build -t frontend ./frontend
